spotify-downloader:
  dry_run: false
  input_ext: automatic
  log_level: INFO
  manual: false
  no_encode: false
  no_metadata: false
  no_spaces: false
  output_ext: mp3
  output_file: storage/music/{artist} - {track-name}.{output-ext}
  overwrite: prompt
  quality: best
  search_format: '{artist} - {track-name} lyrics'
  skip_file: null
  spotify_client_id: 4fe3fecfe5334023a1472516cc99d805
  spotify_client_secret: 0f02b7c483c04257984695007a4a8d5c
  trim_silence: false
  write_successful_file: null
  write_to:
